# Acceptance environment configuration
variables:
  resourceGroupName: 'n8n-rg-acc'
  environment: 'acc'
  environmentName: 'n8n-env-acc'
  containerAppName: 'n8n-app-acc'
  postgresServerName: 'n8n-postgres-acc'
  
  # PostgreSQL credentials (note: password is generated dynamically and stored in Key Vault automatically)
  postgresAdminUsername: 'n8nadmin'
  
  # Key Vault for secrets
  keyVaultName: 'n8n-kv-acc'
  
  # Acceptance specific settings - optimized for testing and staging
  containerCpu: '1.0'
  containerMemory: '2Gi'
  minReplicas: '0'
  maxReplicas: '1'
  
  dryRun: 'false'  # set to false to deploy
