# Production environment configuration
variables:
  resourceGroupName: 'n8n-rg-prd' # TODO to an existing resource group in your subscription
  environment: 'prd'
  environmentName: 'n8n-env-prd'
  containerAppName: 'n8n-app-prd'
  postgresServerName: 'n8n-postgres-prd'
  
  # PostgreSQL credentials (note: password is generated dynamically and stored in Key Vault automatically)
  postgresAdminUsername: 'n8nadmin'
  
  # Key Vault for secrets
  keyVaultName: 'n8n-kv-prd' # TODO Set to an existing key vault in your subscription
  
  # Production specific settings - optimized for production workloads
  containerCpu: '1.0'
  containerMemory: '2Gi'
  minReplicas: '1'
  maxReplicas: '1'
  
  dryRun: 'true' # TODO Set to false to deploy