# Development environment configuration
variables:
  resourceGroupName: 'n8n-rg-dev'
  environment: 'dev'
  environmentName: 'n8n-env-dev'
  containerAppName: 'n8n-app-dev'
  postgresServerName: 'n8n-postgres-dev'
  
  # PostgreSQL credentials (note: password is generated dynamically and stored in Key Vault automatically)
  postgresAdminUsername: 'n8nadmin'
  
  # Key Vault for secrets
  keyVaultName: 'n8n-kv-dev'
  
  # Development specific settings - optimized for development
  containerCpu: '1.0'
  containerMemory: '2Gi'
  minReplicas: '0'
  maxReplicas: '1'
  
  dryRun: 'false'
