# Development environment configuration
variables:
  # Environment specific
  environment: 'dev'
  location: 'westeurope'
  
  # Resource naming with development suffix
  resourceGroupName: 'n8n-rg-dev'
  environmentName: 'n8n-env-dev'
  containerAppName: 'n8n-app-dev'
  postgresServerName: 'n8n-postgres-dev'
  
  # PostgreSQL credentials (password generated dynamically)
  postgresAdminUsername: 'n8nadmin'
  
  # Key Vault for secrets (optional - leave empty to skip Key Vault)
  keyVaultName: 'n8n-kv-dev'
  
  # Development specific settings - optimized for cost and basic functionality
  containerCpu: '1.0'
  containerMemory: '2Gi'
  maxReplicas: '1'
  minReplicas: '0'
  
  # Development domain
  domainName: 'n8n-dev.yourdomain.com'
